### ISSUE TITLE
Crashes when trying to access MyFocuserPro2 Focuser

### ISSUE THREAD

**Issue by theChef613** [farom57/IPARCOS#24]
The app is able to connect to the INDI server but crashes when trying to control any INDI objects.
I used Android Studio to get more information on this. I am currently running Android 9 on my phone so I used API 28. I got an error when trying to build the first time saying "Failed to find Build Tools revision 26.0.2". and fixed it by clicking "Upgrade plugin the version 4.0.1 and sync project" I am adding the error messages from Andoird Studio. When I debug it and connect to my INDI server.
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: farom.iparcos, PID: 7011
    java.lang.IllegalStateException: Fragment farom.iparcos.NumberPropPref.NumberRequestFragment must be a public static class to be  properly recreated from instance state.
        at android.app.BackStackRecord.doAddOp(BackStackRecord.java:429)
        at android.app.BackStackRecord.add(BackStackRecord.java:409)
        at android.app.DialogFragment.show(DialogFragment.java:234)
        at farom.iparcos.NumberPropPref.onClick(NumberPropPref.java:64)
        at android.support.v7.preference.Preference.performClick(Preference.java:1114)
        at android.support.v7.preference.Preference.performClick(Preference.java:1099)
        at android.support.v7.preference.Preference$1.onClick(Preference.java:169)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process: Sending signal. PID: 7011 SIG: 9
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'

**Comment by marcocipriani01** [comment]
Hi, I'm working on an improved IPARCOS fork, test it with your focuser and let me know:
https://github.com/marcocipriani01/IPARCOS
It works fine with my custom focuser, but I don't have a MyFocuserPro2. Feel free to contribute to the project with a pull request!

_Note: I've just updated a lot of libraries and INDIForJava, the app might be unstable._

**Comment by theChef613** [comment]
Hi @marcocipriani01
Thanks for working on this! I know a bit of programming with python and c++ but am totally unfamiliar with Java and android development.
I tried your code and did encounter an error trying to use myfocuserpro2. if you have an arduino i think you can set a test setup pretty easily. see [here](https://sourceforge.net/projects/arduinoascomfocuserpro2diy/).
I'll post an issue on your branch with my results.
Thank you again!

**Comment by farom57** [comment]
The project has been moved to https://github.com/INDIForJava/IPARCOS
